kind: Namespace
apiVersion: v1
metadata:
  annotations:
  name: test
  namespace: default
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-10-1-128-254
  namespace: test
spec:
  config: |-
    {
            "cniVersion": "0.4.0",
            "plugins": [
              {
                "name": "crio",
                "type": "bridge",
                "bridge": "cni1",
                "ipMasq": false,
                "ipam": {
                    "type": "whereabouts",
                    "range": "10.1.128.0/24",
                    "gateway": "10.1.128.254",
                    "log_file": "/tmp/whereabouts.log",
                    "log_level": "debug",
                    "routes": [
                      {
                        "dst": "10.2.128.0/24",
                        "gw": "10.1.128.254"
                      },
                      { "dst": "0.0.0.0/0",
                        "gw": "10.1.128.254"
                      }
                    ],
                    "exclude": [
                      "10.1.128.1/32",
                      "10.1.128.2/32",
                      "10.1.128.254/32"
                    ]
                }
             }
            ]
    }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fos
  name: fos-deployment-254
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fos
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fos-deployment-254
  labels:
      app: fos-254
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
        app: fos-254
  template:
    metadata:
      labels:
        app: fos-254
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-1-128-254-static","namespace": "test" } ]'
    spec:
      containers:
      - name: fos
        image: interbeing/fos:v7231x86

        securityContext:
          capabilities:
              add: ["NET_ADMIN","SYS_ADMIN","NET_RAW"]
        ports:
        - name: isakmp
          containerPort: 500
          protocol: UDP
        - name: ipsec-nat-t
          containerPort: 4500
          protocol: UDP
            #        env:
            #        - name: MY_VAR
            #          valueFrom:
            #            configMapKeyRef:
            #              name: foscfgfirewallvip
            #              key: VAR_CLUSTERIPADDRESS
        volumeMounts:
        - mountPath: /data
          name: data-volume
      imagePullSecrets:
      - name: dockerinterbeing
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: cfosdata
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-10-1-128-254-static
  namespace: test
spec:
  config: |-
    {
            "cniVersion": "0.3.1",
            "name": "crio",
            "type": "bridge",
            "bridge": "cni1",
            "ipMasq": false,
            "ipam": {
                "type": "static",
                "addresses": [
                   {
                      "address": "10.1.128.254/24"
                   }
                ],
                "routes": [
                  { "dst": "1.2.3.4/32","gw":"10.1.128.254" }
                ]
            }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-deployment-254
  labels:
      app: multitool-254
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
        app: multitool-254
  template:
    metadata:
      labels:
        app: multitool-254
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-1-128-254","namespace": "test" } ]'
    spec:
      containers:
        - name: multitool
          image: praqma/network-multitool
          imagePullPolicy: Always
            #command: ["/bin/sh","-c"]
          args:
            - /bin/sh
            - -c
            - /usr/sbin/nginx -g "daemon off;"
          securityContext:
            privileged: true
