---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-deployment-254
  labels:
      app: multitool-254
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
        app: multitool-254
  template:
    metadata:
      labels:
        app: multitool-254
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-1-128-254" } ]'
    spec:
      containers:
        - name: multitool
          image: praqma/network-multitool
          imagePullPolicy: Always
            #command: ["/bin/sh","-c"]
          args:
            - /bin/sh
            - -c
            - /usr/sbin/nginx -g "daemon off;"
          securityContext:
            privileged: true
