---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-10-1-128-2-static
spec:
  config: |-
    {
            "cniVersion": "0.3.1",
            "name": "crio",
            "type": "bridge",
            "bridge": "cni1",
            "ipMasq": false,
            "ipam": {
                "type": "static",
                "addresses": [
                   {
                      "address": "10.1.128.2/24"
                   }
                ],
                "routes": [
                  { "dst": "1.2.3.4/32","gw":"10.1.128.2" }
                ]
            }
    }
