#/bin/bash
export networkName="gkenetwork1" 
export subnetName="gkenode" 
export ipcidrRange="10.0.0.0/24" 
export firewallruleName="$networkName-allow-custom" 
export firewallallowProtocol="all"
export defaultClustername="my-first-cluster-1"
export machineType="e2-standard-2"
export num_nodes="2"
export master_interface_on_worker_node="ens4"
export net_attach_def_name_for_cfos="cfosdefaultcni5"
export custom_dst1='{ "dst": "1.1.1.1/32", "gw": "10.1.200.252" },'
export custom_dst2='{ "dst": "104.18.0.0/16", "gw": "10.1.200.252"},'
export custom_lastdst='{ "dst": "89.238.73.0/24", "gw": "10.1.200.252"}'
export app_nad_annotation="cfosapp"
export cfos_image="interbeing/fos:v7231x86"
export cfosIp="10.1.200.252/32"
export ips_target_url="www.hackthebox.eu"
export webf_target_url="https://www.eicar.org/download/eicar.com.txt"
export internet_webf_url="https://xoso.com.vn"
