---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cfosdefaultcni5
spec:
  config: |-
    {
            "cniVersion": "0.4.0",
            "plugins": [
              {
                "name": "cfosdefaultcni5",
                "type": "bridge",
                "isGateway": false,
                "bridge": "cni5",
                "ipMasq": false,
                "ipam": {
                    "type": "whereabouts",
                    "range": "10.1.128.0/24",
                    "gateway": "10.1.128.2",
                    "log_file": "/tmp/whereabouts.log",
                    "log_level": "debug",
                    "routes": [
                      {
                        "dst": "10.96.0.0/12",
                        "gw": "10.1.128.1"
                      },
                      {
                        "dst": "10.0.0.2/32",
                        "gw": "10.1.128.1"
                      }
                    ],
                    "exclude": [
                      "10.1.128.1/32",
                      "10.1.128.2/32",
                      "10.1.128.254/32"
                    ]
                }
             }
            ]
    }



