apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-default-flannel
spec:
  config: |-
    {
            "cniVersion": "0.4.0",
            "plugins": [
              {
                 "type": "flannel",
                 "name": "flannel.1",
                 "delegate": {
                 "isDefaultGateway": true,
                 "hairpinMode": true
                  }
              },
              {
                "type": "portmap",
                "capabilities": {
                "portMappings": true
                 }
              }
            ]
    }
