---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foscfgfirewallvip
  labels:
    app: fos
    category: config
data:
  type: partial
  config: |-
    config firewall address
          edit "nginxvip"
              set subnet 10.101.222.46 255.255.255.255
          next
    end
