---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foscfgfirewallvip
  labels:
    app: fos
    category: config
data:
  type: partial
  config: |-
    config log setting
        set fwpolicy-implicit-log enable
        set log-invalid-packet enable
        set local-in-allow enable
        set local-in-deny-unicast enable
        set local-in-deny-broadcast enable
        set local-out enable
        set daemon-log enable
        set expolicy-implicit-log enable
    end
