kind: Namespace
apiVersion: v1
metadata:
  annotations:
  name: isolated
  namespace: isolated

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-10-1-128
  namespace: isolated
spec:
  config: |-
    {
            "cniVersion": "0.4.0",
            "plugins": [
              {
                "name": "crio",
                "type": "bridge",
                "bridge": "cni1",
                "ipMasq": false,
                "ipam": {
                    "type": "whereabouts",
                    "range": "10.1.128.0/24",
                    "gateway": "10.1.128.2",
                    "routes": [
                      { "dst": "0.0.0.0/0",
                        "gw": "10.1.128.2"
                      }
                    ],
                    "exclude": [
                      "10.1.128.1/32",
                      "10.1.128.2/32",
                      "10.1.128.254/32"
                    ]
                }
             }
            ]
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-network-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-1-128" } ]'
  namespace: isolated
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: praqma/network-multitool
      name: debug-network-container
      securityContext:
        capabilities:
          add: ["NET_ADMIN","SYS_ADMIN","NET_RAW"]
