apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: default
data:
  .dockerconfigjson: <replace with your base64 encoded config.json file content >
type: kubernetes.io/dockerconfigjson
