region="ap-southeast-1"
instance_type="t3.large" 
cfosLicense="/home/i/202301/deployment/k8s/fos_license.yaml"
key_location="~/.ssh/id_rsa"
dockerinterbeing="/home/i/202301/deployment/private/dockerinterbeing.yaml"
