---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fos01-deployment
  labels:
      app: fos01
spec:
  replicas: 1
  selector:
    matchLabels:
        app: fos01
  template:
    metadata:
      labels:
        app: fos01
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-1-128" , "ips": [ "10.1.128.2/32" ],"mac": "CA:FE:C0:FF:EE:02" } ]'
    spec:
      containers:
      - name: fos01
        image: interbeing/fos:v7231x86

        securityContext:
          capabilities:
              add: ["NET_ADMIN","SYS_ADMIN","NET_RAW"]
        ports:
        - name: isakmp
          containerPort: 500
          protocol: UDP
        - name: ipsec-nat-t
          containerPort: 4500
          protocol: UDP
            #        env:
            #        - name: MY_VAR
            #          valueFrom:
            #            configMapKeyRef:
            #              name: fos01cfgfirewallvip
            #              key: VAR_CLUSTERIPADDRESS
        volumeMounts:
        - mountPath: /data
          name: data-volume
      imagePullSecrets:
      - name: dockerinterbeing
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: cfosdata

