---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fos02-deployment
  labels:
      app: fos02
spec:
  replicas: 1
  selector:
    matchLabels:
        app: fos02
  template:
    metadata:
      labels:
        app: fos02
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-1-128" , "ips": [ "10.1.128.3/32" ],"mac": "CA:FE:C0:FF:EE:03" } ]'
    spec:
      containers:
      - name: fos02
        image: interbeing/fos:v7231x86

        securityContext:
          capabilities:
              add: ["NET_ADMIN","SYS_ADMIN","NET_RAW"]
        ports:
        - name: isakmp
          containerPort: 500
          protocol: UDP
        - name: ipsec-nat-t
          containerPort: 4500
          protocol: UDP
            #        env:
            #        - name: MY_VAR
            #          valueFrom:
            #            configMapKeyRef:
            #              name: fos02cfgfirewallvip
            #              key: VAR_CLUSTERIPADDRESS
        volumeMounts:
        - mountPath: /data
          name: data-volume
      imagePullSecrets:
      - name: dockerinterbeing
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: cfosdata

