---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool02-deployment
  labels:
      app: multitool02
spec:
  replicas: 1
  selector:
    matchLabels:
        app: multitool02
  template:
    metadata:
      labels:
        app: multitool02
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-1-128"  , "default-route": ["10.1.128.3"] } ]'
    spec:
      containers:
        - name: multitool02
          image: praqma/network-multitool
          imagePullPolicy: Always
            #command: ["/bin/sh","-c"]
          args:
            - /bin/sh
            - -c
            - /usr/sbin/nginx -g "daemon off;"
          securityContext:
            privileged: true
