---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool01-deployment
  labels:
      app: multitool01
spec:
  replicas: 1
  selector:
    matchLabels:
        app: multitool01
  template:
    metadata:
      labels:
        app: multitool01
      annotations:
        v1.multus-cni.io/default-network: default/cfosdefaultcni5
        k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-1-128"  , "default-route": ["10.1.128.2"] } ]'
          #k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-1-128" } ]'
    spec:
      containers:
        - name: multitool01
          image: praqma/network-multitool
          imagePullPolicy: Always
            #command: ["/bin/sh","-c"]
          args:
            - /bin/sh
            - -c
            - /usr/sbin/nginx -g "daemon off;"
          securityContext:
            privileged: true
