---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-10-1-128
spec:
  config: |-
    {
            "cniVersion": "0.4.0",
            "plugins": [
              {
                "name": "crio",
                "type": "bridge",
                "bridge": "cni1",
                "mode": "bridge",
                "ipam": {
                    "type": "host-local",
                    "ranges": [
                          [ 
                            {
                             "subnet": "10.1.128.0/24",
                             "rangeStart": "10.1.128.10",
                             "rangeEnd": "10.1.128.20",
                             "gateway": "10.1.128.2"
                            }
                          ]
                    ],
                    "routes": [
                        { "dst": "1.1.1.1/32", "gw": "10.1.128.2" }
                    ],
                    "dataDir": "/run/my-orchestrator/container-ipam-state"
                }
             },
            ] 
    }
