apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "fgt"
spec:
  source:
    http:
      #url: "https://wandy-public-7326-0030-8177.s3.ap-southeast-1.amazonaws.com/fmg707.qcow2" # S3 or GCS
      url: "https://wandy-public-7326-0030-8177.s3.ap-southeast-1.amazonaws.com/fortios611.qcow2" # S3 or GCS
      #url: "https://wandy-public-7326-0030-8177.s3.ap-southeast-1.amazonaws.com/faz74.qcow2" # S3 or GCS
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "3000Mi"
