apiVersion: v1
kind: Service
metadata:
  name: fmg5
spec:
  type: NodePort
  selector:
    app: fmg5 # Replace this with the labels your pod has
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30080
