apiVersion: v1
kind: Service
metadata:
  name: fmg8080
spec:
  type: NodePort
  selector:
    app: fmg # Replace this with the labels your pod has
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
