apiVersion: v1
kind: Service
metadata:
  name: win2k9
spec:
  type: NodePort
  selector:
    app: win2k9 # Replace this with the labels your pod has
  ports:
    - port: 5900
      targetPort: 5900
      nodePort: 30080
