---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-10-1-128
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name": "crio",
            "type": "bridge",
            "bridge": "cni1",
            "ipMasq": false,
            "ipam": {
                "type": "whereabouts",
                "range":     "10.1.128.0/24",
                "exclude": [
                  "10.1.128.1/32",
                  "10.1.128.11/32",
                  "10.1.128.12/32",
                  "10.1.128.254/32"
                ]
            }
        }'
