---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-10-2-128
spec:
  config: |-
    {
            "cniVersion": "0.3.1",
            "name": "crio",
            "type": "bridge",
            "bridge": "cni2",
            "ipMasq": false,
            "ipam": {
                "type": "whereabouts",
                "range": "10.2.128.0/24",
                "gateway": "10.2.128.2",
                "routes": [
                  { 
                    "dst": "10.1.128.0/24",
                    "gw": "10.2.128.2"
                  },
                  { "dst": "1.1.1.1/32",
                    "gw": "10.2.128.2"
                  }
                ],

                "exclude": [
                  "10.2.128.1/32",
                  "10.2.128.2/32",
                  "10.2.128.254/32"
                ]
            }
    }
