kind: Service
apiVersion: v1
metadata:
  name: multus-nginx-bridge-svc
  labels:
    service.kubernetes.io/service-proxy-name: multus-proxy
  annotations:
    k8s.v1.cni.cncf.io/service-network: br-10-2-128
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
