---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-10-2-128-2-static
spec:
  config: |-
    {
            "cniVersion": "0.3.1",
            "name": "crio",
            "type": "bridge",
            "bridge": "cni2",
            "ipMasq": false,
            "ipam": {
                "type": "static",
                  "addresses": [
        {
          "address": "10.2.128.2/24"
        }
      ]
            }
    }
