---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br-10-1-128
spec:
  config: |-
    {
            "cniVersion": "0.4.0",
            "plugins": [
              {
                "name": "crio",
                "type": "bridge",
                "bridge": "cni1",
                "ipMasq": false,
                "ipam": {
                    "type": "whereabouts",
                    "range": "10.1.128.0/24",
                    "gateway": "10.1.128.2",
                    "log_file": "/tmp/whereabouts.log",
                    "log_level": "debug",
                    "routes": [
                      {
                        "dst": "10.2.128.0/24",
                        "gw": "10.1.128.2"
                      },
                      { "dst": "1.1.1.1/32",
                        "gw": "10.1.128.2"
                      }
                    ],
                    "exclude": [
                      "10.1.128.1/32",
                      "10.1.128.2/32",
                      "10.1.128.254/32"
                    ]
                }
             },
             {
               "type": "vrf",
               "vrfname": "test1"
             }
            ]
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: multitool-10-1-128
  annotations:
    k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-1-128" } ]'
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool
    imagePullPolicy: Always
    command: ["/bin/sh","-c"]
    args:
      -  /usr/sbin/nginx -g "daemon off;"
    securityContext:
      privileged: true
