---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-deployment
  labels:
      app: app01
spec:
  replicas: 3
  selector:
    matchLabels:
        app: app01
  template:
    metadata:
      labels:
        app: app01
      annotations:
        #k8s.v1.cni.cncf.io/networks: '[ { "name": "br-10-244-2",  "ips": [ "10.244.2.3/32"], "default-route": ["10.244.2.2"]  } ]'
        v1.multus-cni.io/default-network: default-calico
        #k8s.v1.cni.cncf.io/networks: '[ { "name": "cfosdefaultcni5",  "default-route": ["10.1.128.2"]  } ]'
    spec:
      containers:
        - name: app01
          #image: wbitt/network-test
          image: praqma/network-multitool
            #image: nginx:latest
          imagePullPolicy: Always
            #command: ["/bin/sh","-c"]
          args:
            - /bin/sh
            - -c
            - /usr/sbin/nginx -g "daemon off;"
          securityContext:
            privileged: true
